wandb_version: 1

dataset:
  desc: null
  value: rc
model_name:
  desc: null
  value: FLAMINGO_in_context_same
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.8
    framework: huggingface
    huggingface_version: 4.31.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693216719.717509
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.9.17
      5: 0.15.8
      6: 4.31.0
      8:
      - 5
